/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVendorsRouteImport } from './routes/_app.vendors'
import { Route as AppRfqsRouteImport } from './routes/_app.rfqs'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppQuotationsRouteImport } from './routes/_app.quotations'
import { Route as AppQuotationComparisonRouteImport } from './routes/_app.quotation-comparison'
import { Route as AppPurchaseOrdersRouteImport } from './routes/_app.purchase-orders'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppActivityRouteImport } from './routes/_app.activity'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppRfqsRoute = AppRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationsRoute = AppQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => AppRoute,
} as any)
const AppQuotationComparisonRoute = AppQuotationComparisonRouteImport.update({
  id: '/quotation-comparison',
  path: '/quotation-comparison',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/invoices': typeof AppInvoicesRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/quotation-comparison': typeof AppQuotationComparisonRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/rfqs': typeof AppRfqsRoute
  '/vendors': typeof AppVendorsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/activity': typeof AppActivityRoute
  '/approvals': typeof AppApprovalsRoute
  '/invoices': typeof AppInvoicesRoute
  '/purchase-orders': typeof AppPurchaseOrdersRoute
  '/quotation-comparison': typeof AppQuotationComparisonRoute
  '/quotations': typeof AppQuotationsRoute
  '/reports': typeof AppReportsRoute
  '/rfqs': typeof AppRfqsRoute
  '/vendors': typeof AppVendorsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/activity': typeof AppActivityRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/_app/quotation-comparison': typeof AppQuotationComparisonRoute
  '/_app/quotations': typeof AppQuotationsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/rfqs': typeof AppRfqsRoute
  '/_app/vendors': typeof AppVendorsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/invoices'
    | '/purchase-orders'
    | '/quotation-comparison'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/vendors'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/activity'
    | '/approvals'
    | '/invoices'
    | '/purchase-orders'
    | '/quotation-comparison'
    | '/quotations'
    | '/reports'
    | '/rfqs'
    | '/vendors'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/activity'
    | '/_app/approvals'
    | '/_app/invoices'
    | '/_app/purchase-orders'
    | '/_app/quotation-comparison'
    | '/_app/quotations'
    | '/_app/reports'
    | '/_app/rfqs'
    | '/_app/vendors'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors': {
      id: '/_app/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rfqs': {
      id: '/_app/rfqs'
      path: '/rfqs'
      fullPath: '/rfqs'
      preLoaderRoute: typeof AppRfqsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotations': {
      id: '/_app/quotations'
      path: '/quotations'
      fullPath: '/quotations'
      preLoaderRoute: typeof AppQuotationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quotation-comparison': {
      id: '/_app/quotation-comparison'
      path: '/quotation-comparison'
      fullPath: '/quotation-comparison'
      preLoaderRoute: typeof AppQuotationComparisonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders': {
      id: '/_app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activity': {
      id: '/_app/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppQuotationComparisonRoute: typeof AppQuotationComparisonRoute
  AppQuotationsRoute: typeof AppQuotationsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRfqsRoute: typeof AppRfqsRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppQuotationComparisonRoute: AppQuotationComparisonRoute,
  AppQuotationsRoute: AppQuotationsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRfqsRoute: AppRfqsRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
